name: "Upload Editor's Copy"
on: [push, pull_request]
jobs:
  build:
    name: "Update Editor's Copy"
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@v2

    - name: "Build Drafts"
      uses: martinthomson/i-d-template@v1

    - name: "Update GitHub Pages"
      uses: martinthomson/i-d-template@v1
      with:
        make: gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: "Save HTML"
      uses: actions/upload-artifact@v2
      with:
        path: "*.html"

    - name: "Save Text"
      uses: actions/upload-artifact@v2
      with:
        path: "*.txt"
